[package]
name = "ip2region"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "bench"
harness = false

[dependencies]
speedy = "0.8.2"

[dev-dependencies]
bencher = "0.1.5"